language: haskell
env:
  - 'UBUNTU_RELEASE=saucy GHCVER=7.8.3 CABALVER=1.20'

before_install:
  - 'sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ ${UBUNTU_RELEASE} main universe"'
  - 'sudo add-apt-repository -y ppa:hvr/ghc'
  - 'sudo apt-get update'
  - 'sudo apt-get install librados-dev'
  - 'sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER happy'
  - 'export PATH=/opt/ghc/$GHCVER/bin:$PATH'

install:
  - 'cabal-$CABALVER update'
  - 'cabal sandbox init'
  - 'cabal-$CABALVER install --only-dependencies --enable-tests --enable-benchmarks'

script:
  - 'cabal-$CABALVER configure'
  - 'cabal-$CABALVER build'
  - 'cabal-$CABALVER sdist'
  - 'cabal-$CABALVER test'
